name: "Terraform CI/CD"

on:
  push:
    branches: [ "main", "task_1" ]
  pull_request:
    branches: [ "main", "task_1" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TERRAFORM_VERSION: "1.12.2"
  AWS_ROLE_TO_ASSUME: "arn:aws:iam::897729101221:role/GithubActionsRole"
  AWS_REGION: "us-east-1"
  AWS_ROLE_SESSION_NAME: "GitHubActions"

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - run: terraform fmt -check -recursive

  terraform-plan:
    needs: terraform-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: ${{ env.AWS_ROLE_SESSION_NAME }}

      - run: terraform init

      - run: terraform plan

  terraform-apply:
    needs: terraform-plan
    if: github.ref == 'refs/heads/main && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: ${{ env.AWS_ROLE_SESSION_NAME }}

      - run: terraform init

      - run: terraform apply -auto-approve
