name: test-role

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "task_1" ]
  pull_request:
    branches: [ "main", "task_1" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-oidc:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::897729101221:role/GithubActionsRole
          aws-region: us-east-1

      - name: Who am I
        run: aws sts get-caller-identity